[package]
name = "yoink-server"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = { version = "0.38", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"
futures-util = "0.3"
path-clean = "1"
serde_json = "1"
dashmap = "6"
blake3 = "1"
axum = "0.8"

aes-gcm = { version = "0.10", features = ["stream"], optional = true }
base64 = { version = "0.22", optional = true }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"

[profile.release.package."*"]
opt-level = 3

[features]
default = ["relative"]
relative = []
self_https = ["base64", "aes-gcm"]